# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/taller_nbdev',
                'doc_host': 'https://andfonseca.github.io',
                'git_url': 'https://github.com/andfonseca/taller_nbdev',
                'lib_path': 'taller_nbdev'},
  'syms': { 'taller_nbdev.core': { 'taller_nbdev.core.caracteres_palabra': ('core.html#caracteres_palabra', 'taller_nbdev/core.py'),
                                   'taller_nbdev.core.split_words': ('core.html#split_words', 'taller_nbdev/core.py')}}}
