# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['split_words', 'caracteres_palabra']

# %% ../nbs/00_core.ipynb 3
def split_words(string):
    """Una función que va a dividir todo en sus palabras"""
    return string.split(' ')

# %% ../nbs/00_core.ipynb 6
def caracteres_palabra(string):
    """Caracteres por palabra
    string: Una cadena de caracteres
    returns: Una lista con el número de caracteres por palabra
    """
    list_palabras = split_words(string)
    return [len(palabra) for palabra in list_palabras]
